name: python 3.7
channels:
  - conda-forge
dependencies:
  - python==3.8
  - numpy
  - matplotlib
  - control
  - sympy
  - lxml
  - xlrd
  - networkx
  - scikits.odes
  - pip
  - pip:
    - svgpathtools==1.3.3
    - datetime
    - BondGraphTools
